{% set name = "types-paramiko" %}
{% set version = "3.5.0.20240928" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-paramiko-{{ version }}.tar.gz
  sha256: 79dd9b2ee510b76a3b60d8ac1f3f348c45fcecf01347ca79e14db726bbfc442d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - types-cryptography

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/paramiko-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for paramiko
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
