{% set name = "types-paramiko" %}
{% set version = "3.0.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-paramiko-{{ version }}.tar.gz
  sha256: 1b043cf3c6466babefdbfc7cc21d758019fa4e262568a6fbfe81b9cd1907cb7c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-cryptography

test:
  commands:
    - test -f $SP_DIR/paramiko-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for paramiko
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
