{% set version = "3.5.0.20250801" %}

package:
  name: types-paramiko
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-paramiko/types_paramiko-{{ version }}.tar.gz
  sha256: e79ff84eaf44f2a5ad811743edef5d9c0cd6632a264a526f00405b87db1ec99b

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - cryptography >=37.0.0
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/paramiko-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for paramiko
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
